# api_key: !vault |
#   $ANSIBLE_VAULT;1.1;AES256
#   31363162306238393761346331356264623964633362303830653462306538383537353962616663
#   6366343030386663643138656464643466313534613434300a346330353233313031366632303230
#   35636637356437666533356233636666326632666162613563323532323530386437646332353835
#   6366646430386263340a336436376536653531346564303137306266306364393763393930396334
#   3961
source_dir: /opt/source
soft_dir: /opt/apps
build_dir: /opt/build
home_dir: /home
vpn_conf: secure/vpn.conf
influxdb_database: chambers
influxdb_username: writer
influxdb_password: !vault |
  $ANSIBLE_VAULT;1.1;AES256
  35633032343634373265393232643265386437663432313264336366663334373131633366363835
  3231623063636462376434363932383136633836323564310a306165353966616465326134343463
  65633335363637323764356230396266633236366431633135383935353664623464363731323966
  6130393064633433390a653939613534653531623433326161393730623161356666343537663737
  64646666643236383535386635373761663465623637323432396533343862353533
